name: unit-test
description: "Runs the unit tests on GdUnit4 API"

inputs:
  test-includes:
    description: "The path to include tests to be run"
    required: true
  godot-bin:
    required: true

runs:
  using: composite

  steps:
    - name: "Unit Test Linux"
      if: ${{ runner.OS == 'Linux' }}
      env:
        DISPLAY: :1
        GODOT_BIN: "/home/runner/godot-linux/godot"
      shell: bash
      run: |
        Xvfb :1 -screen 0 1600x1200x24 &
        chmod +x ./runtest.sh
        ./runtest.sh --add ${{ inputs.test-includes }} --display-driver x11 --rendering-driver opengl3 --screen 0 --continue --verbose
        killall Xvfb


# not tested yet
    - name: "Unit Test Windows cmd"
      if: ${{ runner.OS == 'Windows' }}
      env:
        GODOT_BIN: "C:\\Users\\runneradmin/godot-win/godot.exe"
      shell: cmd
      run: |
        echo "%HOMEPATH%"
        set unix_path=${{ inputs.godot-bin }}
        set win_path=%unix_path:~1%
        set win_path=%HOMEPATH%%unix_path:~1%
        set win_path=%win_path:/=\%
        echo "%win_path%"
        echo "%GODOT_BIN%"

        %GODOT_BIN% -s -d .\addons\gdUnit4\bin\GdUnitCmdTool.gd

        
      #  chmod +x ./runtest.cmd
      #  ./runtest.cmd --add ${{ inputs.test-includes }} --continue
      #  set GODOT_BIN=%win_path%
