name: unit-test
description: "Run unit tests for beehave"

inputs:
  test-includes:
    description: "Paths to include for test run"
    required: true
  godot-bin:
    required: true

runs:
  using: composite
  steps:
    - name: "Unit Test"
      env:
        GODOT_BIN: ${{ inputs.godot-bin }}
      shell: bash
      run: chmod +x ./runtest.sh && ./runtest.sh --add ${{ inputs.test-includes }} --continue