name: upload-test-report
description: "Uploads the test reports"

inputs:
  report-name:
    description: "Name of the report to be upload."
    required: true

runs:
  using: composite
  steps:
    - name: Collect Test Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test_report_${{ inputs.report-name }}
        path: reports/**